#if !canImport(ObjectiveC)
import XCTest

extension JobsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JobsTests = [
        ("testScheduleBuilderAPI", testScheduleBuilderAPI),
        ("testVaporIntegration", testVaporIntegration),
    ]
}

extension ScheduleBuilderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ScheduleBuilderTests = [
        ("testDailyBuilder", testDailyBuilder),
        ("testHourlyBuilder", testHourlyBuilder),
        ("testMonthlyBuilder15th", testMonthlyBuilder15th),
        ("testMonthlyBuilderFirstDay", testMonthlyBuilderFirstDay),
        ("testWeeklyBuilder", testWeeklyBuilder),
        ("testYearlyBuilder", testYearlyBuilder),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JobsTests.__allTests__JobsTests),
        testCase(ScheduleBuilderTests.__allTests__ScheduleBuilderTests),
    ]
}
#endif
